### ISSUE TITLE
keystore password is not passed on in SslContextUtils.buildMergedWithSystem(..)

### ISSUE THREAD

**Issue by goekay** [1and1/CompositeJKS#4]
current impl inits a keymanager for the customer keystore [without setting the password](https://github.com/1and1/CompositeJKS/blob/6e5314d7615d90f368324ff9b142cc9bbc086cfc/src/main/java/com/oneandone/compositejks/SslContextUtils.java#L77) even though the keystore might have one. because of this, `java.security.UnrecoverableKeyException: Password must not be null ` occurs.

in our project, we fixed this by [adding a param to the method](https://github.com/RWTH-i5-IDSG/steve/blob/8ad7c836afef029da00a26b7761ec53c83163335/src/main/java/de/rwth/idsg/steve/ocpp/soap/ClientProvider.java#L93-L106). i think it's useful to apply it here, as well.

**Comment by lauksas** [comment]
Same problem here, I would use the version 1.0 and override this method if the class wan't final... such a nice utility...
The only option I have is copy the code inside my project like @goekay did.
Thanks for the sharing BTW!

**Comment by goekay** [comment]
@lauksas i extracted the code from our project into [my fork](https://github.com/goekay/CompositeJKS) including my API changes from #6. feel free to use it.
